site_name: Longmetal Docs
theme:
  name: material
  palette:
    primary: blue
  logo: assets/logo.svg
  features:
    - search.suggest


markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - search
#  - pdf-export
